"""
Runtime persistence.
"""
import datetime


class Package:
    """Wrapper for persisting runtime state representation.
    """
    def __init__(self):
        self.project = ...
        self.trained: datetime.datetime = ...
        self.tuned: datetime.datetime = ...
        self.ordinal = ...
        self.states = ...
