import datetime


class Package:
    def __init__(self):
        self.project = ...
        self.trained: datetime.datetime = ...
        self.tuned: datetime.datetime = ...
        self.ordinal = ...
        self.states = ...